config/routes.rb
Rails.application.routes.draw do

  mount Notifications::Engine => "/notifications"
  root "categories#bad"
  devise_for :users

  resources :users

  post '/users/:id/follow_user', to: 'followers#follow_user', as: :follow_user
  post '/users/:id/unfollow_user', to: 'followers#unfollow_user', as: :unfollow_user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories, only: :show, path: "" do
    resources :stories do
      resources :comments, only: :create

      post '/up_vote/:id', to: 'votes#create_up', as: 'up'
      post '/down_vote/:id', to: 'votes#create_down', as: 'down'
    end
  end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :stories
  validates :name, inclusion: { in: %w(bad good) }
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/city.rb
class City < ApplicationRecord
  has_many :locations, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :story
  belongs_to :user
  validates :body, presence: true, length: {minimum: 5, maximum: 500}

  after_commit :create_notifications, on: [:create]

  private

  def create_notifications
    Notification.create(
      notify_type: 'story',
      actor: self.user,
      user: self.story.user,
      target: self,
      second_target: self.story)
  end
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
  # belongs_to :location
  belongs_to :followable, polymorphic: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :stories, dependent: :destroy
  belongs_to :city
end

app/models/notification.rb
# Auto generate with notifications gem.
class Notification < ActiveRecord::Base
  include Notifications::Model

  # Write your custom methods...
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :location
  has_one_attached :picture
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  attr_accessor :latitude, :longitude
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stories, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :followers, dependent: :destroy

  def follow(user)
    followers.create(followable: user)
    Notification.create(notify_type: 'follower', actor: self, user: user)
  end

  def unfollow(user)
    followers.find_by(followable: user).destroy
  end

  def follow?(user)
    followers.where(followable: user).exists?
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :story
  belongs_to :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.friendly.find(params[:id])
    ranking
  end

  def bad
     redirect_to category_path(Category.first)
  end

  private

  def ranking
    @how_many_in_ranking = 10
    @stories_in_cat = @category.stories.count

    story_hash = {}
    @category.stories.each do |story|
      points = 0
      story.votes.each { |vote| vote.updown == true ? points += 1 : points -= 1}
      story_hash[story] = points
    end

    @rank = story_hash.sort_by {|_key, value| value}
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_category

  def create
    @story = Story.find(params[:story_id])
    @comment = @story.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:success] = "Comment added succesfully"
    else
      flash[:danger] = "#{@comment.errors.full_messages.first}"
    end
    redirect_to category_story_path(@category, @story)

  end

  private
    def comment_params
      params.require(:comment).permit(:body, :user_id, :story_id)
    end

    def set_category
      @category = Category.friendly.find(params[:category_id])
    end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def follow_user
    @user = User.find_by! id: params[:id]
    if current_user.follow @user
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow_user
    @user = User.find_by! id: params[:id]
    if current_user.unfollow @user
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_category

def new
  @story = Story.new
  @location = Location.new
  @last_location = last_location
end

def show
  @story = Story.find(params[:id])
  @comments = @story.comments
end

def create
  city_name = Geocoder.search("#{params[:story][:latitude]},#{params[:story][:longitude]}").first.city
  city_name = "almost nowhere" if city_name.nil?
  @city = City
            .where(name: city_name).first || City.create(name: city_name)
  @location = Location
                .where(latitude: params[:story][:latitude])
                .where(longitude: params[:story][:longitude])
                .first ||
              Location
                .create(latitude: params[:story][:latitude],
                        longitude: params[:story][:longitude],
                        city: @city)
  @story = current_user.stories.build(story_params)
  @story.category = @category
  @story.location = @location
  if @story.save
    flash[:success] = "Story was successfully added. Look for it below. :) "
    redirect_to category_path(@category.id)
  else
    render 'new'
  end

end

private
  def story_params
    params.require(:story).permit(:title, :text, :category, :picture, :user_id, :location_id)
  end

  def set_category
    @category = Category.friendly.find(params[:category_id])
  end

  # Set up marker in last location
  def last_location
    if !current_user.stories.last.nil?
      current_user.stories.last.location
    else
      Location.new(latitude: 53.1235, longitude: 18.0084)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :find_story

  def create_up
    if already_voted?
      flash[:notice] = "You can't vote more than once"
    else
      flash[:success] = "Thanks for voting"
      @story.votes.create(user_id: current_user.id, updown: true)
    end

    redirect_to category_story_path(Category.find(params[:category_id]), @story.id)

  end

  def create_down
    if already_voted?
      flash[:notice] = "You can't vote more than once"
    else
      flash[:success] = "Thanks for voting"
      @story.votes.create(user_id: current_user.id, updown: false)
    end

    redirect_to category_story_path(Category.find(params[:category_id]), @story.id)
  end

  private

  def already_voted?
    Vote.where(user_id: current_user.id, story_id:
    params[:story_id]).exists?
  end

  def find_story
    @story = Story.find(params[:story_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follow/_follow_toggle.html.erb
<% unless @user == current_user %>
	<span class="follows" id="#user_<%= @user.id %>">
		<% if current_user.follow?(@user) %>
			<%= link_to 'Unfollow', unfollow_user_path(@user.id),
			class: 'btn unfollow-btn btn-sm',
			id: 'unfollow-button',
			method: :post,
			remote: true %>
		<% else %>
			<%= link_to 'Follow', follow_user_path(@user.id),
			class: 'btn follow-btn btn-sm',
			id: 'follow-button',
			method: :post,
			remote: true %>
		<% end %>
	</span>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
  <div class="alert alert-<%= key %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <footer class="footer">
    <p>Made by Team Dogung:
      <a href="https://github.com/railsgirl">Paulina</a>,
      <a href="https://github.com/jjkazm">Jakub</a>,
      <a href="https://github.com/MrkKr">Marek</a>,
      <a href="https://github.com/MDrawc">Michal</a>
    </p>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<%if @category != nil
    if @category.name == "bad"
      help_nav = "background: linear-gradient(to right, #b8daff, #f8f9fa);"
      help_bad = "bad_a btn btn-outline-primary" + " " + "active"
      help_good = "good btn btn-outline-danger"
    else
      help_nav = "background: linear-gradient(to right, #f5c6cb, #f8f9fa);"
      help_bad = "bad btn btn-outline-primary"
      help_good = "good_a btn btn-outline-danger" + " " + "active"
    end
  else
    help_nav = "background-color: #f8f9fa"
    help_bad = "bad btn btn-outline-primary"
    help_good = "good btn btn-outline-danger"
  end%>

  <nav class="navbar navbar-expand-lg navbar-light" style="<%= help_nav %>">
    <ul class="nav nav-pills">
      <li class="nav-item" id="logo_switch">
        <%= link_to "So Bad", main_app.category_path("bad"), class: help_bad %>
      </li>
      <li class="nav-item" id="logo_switch">
        <%= link_to "So Good", main_app.category_path("good"), class: help_good %>
      </li>
    </ul>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <% if user_signed_in? %>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My following users</a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <% if current_user.followers.any? %>
                <% current_user.followers.each do |follower| %>
                  <%= link_to follower.followable.username,
                  main_app.user_path(follower.followable),
                  class: "dropdown-item" %>
                <% end %>
              <% else %>
                <a class="dropdown-item" href="#">You don't follow any user</a>
              <% end %>
            </div>
          </div>
          <% if @category != nil %>
            <li class="nav-item">
              <%= link_to "Share Story", main_app.new_category_story_path(@category.name), class: "nav-link" %>
            </li>
          <% else %>
          <% end %>
          <li class="nav-item">
            <%= link_to "My stories", main_app.user_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cities", main_app.root_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav text-right">
          <li class="nav-item">
            <%= link_to pluralize(Notification.unread_count(current_user), 'Notification'), notifications_path, :class => Notification.unread_count(current_user) > 0 ? 'badge badge-success mr-3' : 'badge badge-danger mr-3' %>
          </li>
          <p class="navbar-text">Logged in as
            <strong><%= current_user.username %></strong>
          </p>
          <li class="nav-item">
            <%= link_to 'Edit profile', main_app.edit_user_registration_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", main_app.destroy_user_session_path, method: :delete, :class => "nav-link" %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to "Cities", main_app.root_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav text-right">
          <li class="nav-item">
            <%= link_to 'Login', main_app.new_user_session_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", main_app.new_user_registration_path, :class => "nav-link" %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoBadSoGood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/navigation" %>
      <%= render "layouts/flash" %>
      <div class="container-fluid">
      <%= yield %>
      </div>
    <%= render "layouts/footer"%>
  </body>
</html>